"""Postgres UnitOfWork / repositories (sync SQLAlchemy engine + psycopg).

Same ports as SqliteUnitOfWork. Configure via DATABASE_URL, e.g.:
  postgresql+psycopg://user:pass@host:5432/auto_apply_app
Railway often provides postgresql://… — normalized in settings/factory.
"""

from __future__ import annotations

import json
import logging
import time
from collections.abc import Iterator, Mapping
from contextlib import contextmanager
from pathlib import Path
from typing import Any

from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine

from app.domain.entities import (
    Application,
    JobState,
    JournalEntry,
    LinkedInContact,
    LinkedInVacancyLink,
    Profile,
    Vacancy,
    normalize_journal_service,
)
from app.domain.enums import ApplyStatus, FitCategory, JobStatus

log = logging.getLogger(__name__)

RowLike = Mapping[str, Any]


def normalize_postgres_url(url: str) -> str:
    """Normalize Railway/Heroku-style URLs to SQLAlchemy + psycopg driver."""
    raw = (url or "").strip()
    if not raw:
        raise ValueError("empty DATABASE_URL")
    if raw.startswith("postgres://"):
        raw = "postgresql://" + raw[len("postgres://") :]
    if raw.startswith("postgresql+psycopg://"):
        return raw
    if raw.startswith("postgresql+asyncpg://"):
        raise ValueError(
            "asyncpg URL is not supported (ports are sync). "
            "Use postgresql+psycopg://… or postgresql://…"
        )
    if raw.startswith("postgresql://"):
        return "postgresql+psycopg://" + raw[len("postgresql://") :]
    raise ValueError(
        f"Unsupported Postgres DATABASE_URL={url!r}. "
        "Expected postgresql://… or postgresql+psycopg://…"
    )


def create_postgres_engine(url: str, *, echo: bool = False) -> Engine:
    """Create a sync SQLAlchemy engine (psycopg3)."""
    sa_url = normalize_postgres_url(url)
    return create_engine(
        sa_url,
        pool_pre_ping=True,
        pool_size=5,
        max_overflow=10,
        future=True,
        echo=echo,
    )


class PostgresUnitOfWork:
    """Sync Postgres adapter implementing the same UnitOfWork ports as SQLite."""

    def __init__(
        self,
        database_url: str,
        *,
        engine: Engine | None = None,
        reset: bool = False,
        echo: bool = False,
    ) -> None:
        self.database_url = database_url
        self.engine = engine or create_postgres_engine(database_url, echo=echo)
        self.profiles = _ProfileRepo(self)
        self.vacancies = _VacancyRepo(self)
        self.applications = _ApplicationRepo(self)
        self.jobs = _JobStateRepo(self)
        self.journal = _JournalRepo(self)
        self.linkedin_contacts = _LinkedInContactRepo(self)
        self.linkedin_vacancies = _LinkedInVacancyRepo(self)
        self.report_files = _ReportFileRepo(self)
        if reset:
            log.warning("RESET_DB=true — dropping public schema on Postgres")
            self._reset_schema()
        self._init_schema()
        if not self.profiles.list_profiles():
            self.profiles.ensure_profile("default")
            log.info("Initialized empty Postgres schema (default profile)")

    def dispose(self) -> None:
        self.engine.dispose()

    @contextmanager
    def _conn(self) -> Iterator[Any]:
        with self.engine.begin() as conn:
            yield conn

    def _reset_schema(self) -> None:
        with self.engine.begin() as conn:
            conn.execute(text("DROP SCHEMA IF EXISTS public CASCADE"))
            conn.execute(text("CREATE SCHEMA public"))

    def _init_schema(self) -> None:
        with self._conn() as c:
            c.execute(
                text(
                    """
                    CREATE TABLE IF NOT EXISTS profiles (
                        name TEXT PRIMARY KEY,
                        created_at DOUBLE PRECISION NOT NULL,
                        storage_path TEXT,
                        storage_saved_at DOUBLE PRECISION,
                        notes TEXT
                    );
                    """
                )
            )
            c.execute(
                text(
                    """
                    CREATE TABLE IF NOT EXISTS vacancies (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        profile TEXT NOT NULL,
                        vacancy_id TEXT,
                        url TEXT NOT NULL,
                        title TEXT,
                        description TEXT,
                        query TEXT,
                        serp_url TEXT,
                        category TEXT NOT NULL DEFAULT 'LOW',
                        score INTEGER NOT NULL DEFAULT 0,
                        category_reason TEXT,
                        filter_status TEXT NOT NULL DEFAULT 'pending',
                        apply_status TEXT NOT NULL DEFAULT 'queued',
                        created_at DOUBLE PRECISION NOT NULL,
                        updated_at DOUBLE PRECISION NOT NULL,
                        UNIQUE(profile, url)
                    );
                    """
                )
            )
            c.execute(
                text(
                    "CREATE INDEX IF NOT EXISTS idx_vac_profile ON vacancies(profile)"
                )
            )
            c.execute(
                text(
                    "CREATE INDEX IF NOT EXISTS idx_vac_cat ON vacancies(category, score)"
                )
            )
            c.execute(
                text(
                    "CREATE INDEX IF NOT EXISTS idx_vac_vid ON vacancies(profile, vacancy_id)"
                )
            )
            c.execute(
                text(
                    """
                    CREATE TABLE IF NOT EXISTS applications (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        profile TEXT NOT NULL,
                        vacancy_url TEXT NOT NULL,
                        vacancy_id TEXT,
                        title TEXT,
                        category TEXT,
                        status TEXT NOT NULL,
                        attempt INTEGER DEFAULT 1,
                        error TEXT,
                        dry_run INTEGER DEFAULT 0,
                        duration_ms INTEGER,
                        created_at DOUBLE PRECISION NOT NULL
                    );
                    """
                )
            )
            c.execute(
                text(
                    "CREATE INDEX IF NOT EXISTS idx_app_profile ON applications(profile)"
                )
            )
            c.execute(
                text(
                    """
                    CREATE TABLE IF NOT EXISTS journal (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ts DOUBLE PRECISION NOT NULL,
                        profile TEXT NOT NULL,
                        level TEXT NOT NULL DEFAULT 'info',
                        event TEXT NOT NULL,
                        message TEXT,
                        payload TEXT,
                        service TEXT NOT NULL DEFAULT 'hh'
                    );
                    """
                )
            )
            c.execute(text("CREATE INDEX IF NOT EXISTS idx_journal_ts ON journal(ts)"))
            c.execute(
                text(
                    """
                    CREATE INDEX IF NOT EXISTS idx_journal_service
                        ON journal(profile, service, ts)
                    """
                )
            )
            c.execute(
                text(
                    """
                    CREATE TABLE IF NOT EXISTS job_state (
                        profile TEXT PRIMARY KEY,
                        status TEXT NOT NULL DEFAULT 'idle',
                        message TEXT,
                        stats_json TEXT,
                        updated_at DOUBLE PRECISION NOT NULL
                    );
                    """
                )
            )
            c.execute(
                text(
                    """
                    CREATE TABLE IF NOT EXISTS meta (
                        key TEXT PRIMARY KEY,
                        value TEXT
                    );
                    """
                )
            )
            c.execute(
                text(
                    """
                    CREATE TABLE IF NOT EXISTS linkedin_contacts (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        profile TEXT NOT NULL,
                        url TEXT NOT NULL,
                        name TEXT,
                        headline TEXT,
                        location TEXT,
                        query TEXT,
                        status TEXT NOT NULL DEFAULT 'pending',
                        error TEXT,
                        created_at DOUBLE PRECISION NOT NULL,
                        updated_at DOUBLE PRECISION NOT NULL,
                        UNIQUE(profile, url)
                    );
                    """
                )
            )
            c.execute(
                text(
                    """
                    CREATE INDEX IF NOT EXISTS idx_li_contacts_profile
                        ON linkedin_contacts(profile)
                    """
                )
            )
            c.execute(
                text(
                    """
                    CREATE TABLE IF NOT EXISTS linkedin_vacancies (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        profile TEXT NOT NULL,
                        url TEXT NOT NULL,
                        title TEXT,
                        company TEXT,
                        location TEXT,
                        query TEXT,
                        source TEXT NOT NULL DEFAULT 'linkedin',
                        created_at DOUBLE PRECISION NOT NULL,
                        updated_at DOUBLE PRECISION NOT NULL,
                        UNIQUE(profile, url)
                    );
                    """
                )
            )
            c.execute(
                text(
                    """
                    CREATE INDEX IF NOT EXISTS idx_li_vac_profile
                        ON linkedin_vacancies(profile)
                    """
                )
            )
            c.execute(
                text(
                    """
                    CREATE TABLE IF NOT EXISTS report_files (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        profile TEXT NOT NULL,
                        kind TEXT NOT NULL,
                        path TEXT NOT NULL,
                        created_at DOUBLE PRECISION NOT NULL,
                        scheduled INTEGER NOT NULL DEFAULT 0
                    );
                    """
                )
            )
            c.execute(
                text(
                    """
                    CREATE INDEX IF NOT EXISTS idx_report_files_ts
                        ON report_files(created_at)
                    """
                )
            )
            self._migrate_journal_service(c)

    @staticmethod
    def _migrate_journal_service(c: Any) -> None:
        row = c.execute(
            text(
                """
                SELECT 1 FROM information_schema.columns
                WHERE table_schema='public' AND table_name='journal'
                  AND column_name='service'
                """
            )
        ).fetchone()
        if not row:
            c.execute(
                text(
                    "ALTER TABLE journal ADD COLUMN service TEXT NOT NULL DEFAULT 'hh'"
                )
            )
            c.execute(
                text(
                    """
                    UPDATE journal SET service='linkedin'
                    WHERE lower(event) LIKE 'linkedin_%'
                    """
                )
            )

    def stats(self, profile: str) -> dict[str, Any]:
        return self.applications.stats(profile)

    def get_meta(self, key: str) -> str | None:
        with self._conn() as c:
            row = c.execute(
                text("SELECT value FROM meta WHERE key=:key"),
                {"key": key},
            ).mappings().fetchone()
            return str(row["value"]) if row and row["value"] is not None else None

    def set_meta(self, key: str, value: str) -> None:
        with self._conn() as c:
            c.execute(
                text(
                    """
                    INSERT INTO meta(key, value) VALUES (:key, :value)
                    ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value
                    """
                ),
                {"key": key, "value": value},
            )


class _ProfileRepo:
    def __init__(self, uow: PostgresUnitOfWork) -> None:
        self._uow = uow

    def list_profiles(self) -> list[Profile]:
        with self._uow._conn() as c:
            rows = (
                c.execute(text("SELECT * FROM profiles ORDER BY name"))
                .mappings()
                .fetchall()
            )
            return [_row_profile(r) for r in rows]

    def ensure_profile(self, name: str) -> Profile:
        name = _clean_profile_name(name, fallback="default")
        now = time.time()
        with self._uow._conn() as c:
            c.execute(
                text(
                    """
                    INSERT INTO profiles(name, created_at) VALUES (:name, :ts)
                    ON CONFLICT(name) DO NOTHING
                    """
                ),
                {"name": name, "ts": now},
            )
            c.execute(
                text(
                    """
                    INSERT INTO job_state(profile, status, message, stats_json, updated_at)
                    VALUES (:name, 'idle', '', '{}', :ts)
                    ON CONFLICT(profile) DO NOTHING
                    """
                ),
                {"name": name, "ts": now},
            )
            row = (
                c.execute(
                    text("SELECT * FROM profiles WHERE name=:name"),
                    {"name": name},
                )
                .mappings()
                .fetchone()
            )
            assert row is not None
            return _row_profile(row)

    def resolve_profile(self, name: str | None = None) -> str:
        wanted = (name or "").strip()
        existing = self.list_profiles()
        names = [p.name for p in existing]
        if not names:
            return self.ensure_profile(wanted or "default").name
        if wanted and wanted in names:
            return wanted
        return names[0]

    def rename_profile(self, old_name: str, new_name: str) -> Profile:
        old_name = _clean_profile_name(old_name)
        new_name = _clean_profile_name(new_name)
        with self._uow._conn() as c:
            old = (
                c.execute(
                    text("SELECT * FROM profiles WHERE name=:name"),
                    {"name": old_name},
                )
                .mappings()
                .fetchone()
            )
            if not old:
                raise ValueError(f"profile not found: {old_name}")
            if old_name == new_name:
                return _row_profile(old)
            exists = c.execute(
                text("SELECT 1 FROM profiles WHERE name=:name"),
                {"name": new_name},
            ).fetchone()
            if exists:
                raise ValueError(f"profile already exists: {new_name}")
            for table in (
                "vacancies",
                "applications",
                "journal",
                "job_state",
                "linkedin_contacts",
                "linkedin_vacancies",
                "report_files",
            ):
                c.execute(
                    text(f"UPDATE {table} SET profile=:new WHERE profile=:old"),
                    {"new": new_name, "old": old_name},
                )
            c.execute(
                text("UPDATE profiles SET name=:new WHERE name=:old"),
                {"new": new_name, "old": old_name},
            )
            row = (
                c.execute(
                    text("SELECT * FROM profiles WHERE name=:name"),
                    {"name": new_name},
                )
                .mappings()
                .fetchone()
            )
            assert row is not None
            return _row_profile(row)

    def delete_profile(self, name: str) -> str:
        name = _clean_profile_name(name)
        with self._uow._conn() as c:
            row = c.execute(
                text("SELECT name FROM profiles WHERE name=:name"),
                {"name": name},
            ).fetchone()
            if not row:
                raise ValueError(f"profile not found: {name}")
            for table in (
                "vacancies",
                "applications",
                "journal",
                "job_state",
                "linkedin_contacts",
                "linkedin_vacancies",
                "report_files",
            ):
                c.execute(
                    text(f"DELETE FROM {table} WHERE profile=:name"),
                    {"name": name},
                )
            c.execute(
                text("DELETE FROM profiles WHERE name=:name"),
                {"name": name},
            )
            remaining = (
                c.execute(text("SELECT name FROM profiles ORDER BY name"))
                .mappings()
                .fetchall()
            )
            if not remaining:
                now = time.time()
                c.execute(
                    text("INSERT INTO profiles(name, created_at) VALUES (:name, :ts)"),
                    {"name": "default", "ts": now},
                )
                c.execute(
                    text(
                        """
                        INSERT INTO job_state(profile, status, message, stats_json, updated_at)
                        VALUES (:name, 'idle', '', '{}', :ts)
                        """
                    ),
                    {"name": "default", "ts": now},
                )
                return "default"
            return str(remaining[0]["name"])

    def save_session(self, profile: str, storage_path: Path) -> None:
        with self._uow._conn() as c:
            c.execute(
                text(
                    """
                    UPDATE profiles
                    SET storage_path=:path, storage_saved_at=:ts
                    WHERE name=:name
                    """
                ),
                {"path": str(storage_path), "ts": time.time(), "name": profile},
            )

    def get_session_path(self, profile: str) -> str | None:
        with self._uow._conn() as c:
            row = (
                c.execute(
                    text("SELECT storage_path FROM profiles WHERE name=:name"),
                    {"name": profile},
                )
                .mappings()
                .fetchone()
            )
            return row["storage_path"] if row and row["storage_path"] else None


class _VacancyRepo:
    def __init__(self, uow: PostgresUnitOfWork) -> None:
        self._uow = uow

    def upsert(self, vacancy: Vacancy) -> int:
        now = time.time()
        cat = (
            vacancy.category.value
            if isinstance(vacancy.category, FitCategory)
            else str(vacancy.category)
        )
        apply = (
            vacancy.apply_status.value
            if isinstance(vacancy.apply_status, ApplyStatus)
            else str(vacancy.apply_status)
        )
        with self._uow._conn() as c:
            c.execute(
                text(
                    """
                    INSERT INTO vacancies(
                        profile, vacancy_id, url, title, description, query, serp_url,
                        category, score, category_reason, filter_status, apply_status,
                        created_at, updated_at
                    ) VALUES (
                        :profile, :vacancy_id, :url, :title, :description, :query, :serp_url,
                        :category, :score, :category_reason, :filter_status, :apply_status,
                        :created_at, :updated_at
                    )
                    ON CONFLICT(profile, url) DO UPDATE SET
                        title=COALESCE(EXCLUDED.title, vacancies.title),
                        description=COALESCE(EXCLUDED.description, vacancies.description),
                        category=EXCLUDED.category,
                        score=EXCLUDED.score,
                        category_reason=EXCLUDED.category_reason,
                        filter_status=EXCLUDED.filter_status,
                        apply_status=CASE
                            WHEN vacancies.apply_status IN ('applied','dry_run')
                                THEN vacancies.apply_status
                            ELSE EXCLUDED.apply_status
                        END,
                        updated_at=EXCLUDED.updated_at
                    """
                ),
                {
                    "profile": vacancy.profile,
                    "vacancy_id": vacancy.vacancy_id,
                    "url": vacancy.url,
                    "title": vacancy.title,
                    "description": vacancy.description,
                    "query": vacancy.query,
                    "serp_url": vacancy.serp_url,
                    "category": cat,
                    "score": int(vacancy.score),
                    "category_reason": vacancy.category_reason,
                    "filter_status": vacancy.filter_status,
                    "apply_status": apply,
                    "created_at": now,
                    "updated_at": now,
                },
            )
            row = (
                c.execute(
                    text(
                        "SELECT id FROM vacancies WHERE profile=:profile AND url=:url"
                    ),
                    {"profile": vacancy.profile, "url": vacancy.url},
                )
                .mappings()
                .fetchone()
            )
            assert row is not None
            return int(row["id"])

    def exists(
        self,
        profile: str,
        *,
        url: str | None = None,
        vacancy_id: str | None = None,
    ) -> bool:
        url = (url or "").strip()
        vacancy_id = (vacancy_id or "").strip()
        if not url and not vacancy_id:
            return False
        with self._uow._conn() as c:
            if url and vacancy_id:
                row = c.execute(
                    text(
                        """
                        SELECT 1 FROM vacancies
                        WHERE profile=:profile AND (url=:url OR vacancy_id=:vid)
                        LIMIT 1
                        """
                    ),
                    {"profile": profile, "url": url, "vid": vacancy_id},
                ).fetchone()
            elif vacancy_id:
                row = c.execute(
                    text(
                        """
                        SELECT 1 FROM vacancies
                        WHERE profile=:profile AND vacancy_id=:vid
                        LIMIT 1
                        """
                    ),
                    {"profile": profile, "vid": vacancy_id},
                ).fetchone()
            else:
                row = c.execute(
                    text(
                        """
                        SELECT 1 FROM vacancies
                        WHERE profile=:profile AND url=:url
                        LIMIT 1
                        """
                    ),
                    {"profile": profile, "url": url},
                ).fetchone()
        return row is not None

    def known_keys(self, profile: str) -> tuple[set[str], set[str]]:
        with self._uow._conn() as c:
            rows = (
                c.execute(
                    text("SELECT url, vacancy_id FROM vacancies WHERE profile=:profile"),
                    {"profile": profile},
                )
                .mappings()
                .fetchall()
            )
        urls: set[str] = set()
        ids: set[str] = set()
        for r in rows:
            u = (r["url"] or "").strip()
            if u:
                urls.add(u)
            vid = (r["vacancy_id"] or "").strip()
            if vid:
                ids.add(vid)
        return urls, ids

    def list_for_profile(
        self,
        profile: str,
        *,
        apply_status: str | None = None,
        limit: int = 200,
        offset: int = 0,
    ) -> list[Vacancy]:
        with self._uow._conn() as c:
            sql = "SELECT * FROM vacancies WHERE profile=:profile"
            params: dict[str, Any] = {"profile": profile}
            if apply_status:
                sql += " AND apply_status=:apply_status"
                params["apply_status"] = apply_status
            rows = c.execute(text(sql), params).mappings().fetchall()
        items = [_row_vacancy(r) for r in rows]
        items.sort(key=lambda v: (v.category.priority, -v.score, v.id or 0))
        return items[offset : offset + limit]

    def next_queued(self, profile: str, limit: int = 100) -> list[Vacancy]:
        return [
            v
            for v in self.list_for_profile(
                profile, apply_status="queued", limit=limit * 2
            )
            if v.filter_status == "ok"
        ][:limit]

    def set_apply_status(self, vacancy_pk: int, status: str) -> None:
        with self._uow._conn() as c:
            c.execute(
                text(
                    """
                    UPDATE vacancies
                    SET apply_status=:status, updated_at=:ts
                    WHERE id=:id
                    """
                ),
                {"status": status, "ts": time.time(), "id": vacancy_pk},
            )


class _ApplicationRepo:
    def __init__(self, uow: PostgresUnitOfWork) -> None:
        self._uow = uow

    def already_applied(self, profile: str, vacancy_url: str) -> bool:
        with self._uow._conn() as c:
            row = c.execute(
                text(
                    """
                    SELECT 1 FROM applications
                    WHERE profile=:profile AND vacancy_url=:url
                      AND (status IN ('applied','skipped','dry_run')
                           OR status LIKE 'filtered:%')
                    LIMIT 1
                    """
                ),
                {"profile": profile, "url": vacancy_url},
            ).fetchone()
            return row is not None

    def count_applied_since(self, profile: str, since_ts: float) -> int:
        with self._uow._conn() as c:
            row = (
                c.execute(
                    text(
                        """
                        SELECT COUNT(*) AS n FROM applications
                        WHERE profile=:profile AND status='applied'
                          AND dry_run=0 AND created_at>=:since
                        """
                    ),
                    {"profile": profile, "since": since_ts},
                )
                .mappings()
                .fetchone()
            )
            return int(row["n"]) if row else 0

    def record(self, application: Application) -> None:
        with self._uow._conn() as c:
            c.execute(
                text(
                    """
                    INSERT INTO applications(
                        profile, vacancy_url, vacancy_id, title, category,
                        status, attempt, error, dry_run, duration_ms, created_at
                    ) VALUES (
                        :profile, :vacancy_url, :vacancy_id, :title, :category,
                        :status, :attempt, :error, :dry_run, :duration_ms, :created_at
                    )
                    """
                ),
                {
                    "profile": application.profile,
                    "vacancy_url": application.vacancy_url,
                    "vacancy_id": application.vacancy_id,
                    "title": application.title,
                    "category": application.category,
                    "status": application.status,
                    "attempt": application.attempt,
                    "error": application.error,
                    "dry_run": int(application.dry_run),
                    "duration_ms": application.duration_ms,
                    "created_at": time.time(),
                },
            )

    def stats(self, profile: str) -> dict[str, Any]:
        with self._uow._conn() as c:
            by_cat = {
                r["category"]: r["n"]
                for r in c.execute(
                    text(
                        """
                        SELECT category, COUNT(*) AS n FROM vacancies
                        WHERE profile=:profile AND filter_status='ok'
                        GROUP BY category
                        """
                    ),
                    {"profile": profile},
                ).mappings()
            }
            by_apply = {
                r["apply_status"]: r["n"]
                for r in c.execute(
                    text(
                        """
                        SELECT apply_status, COUNT(*) AS n FROM vacancies
                        WHERE profile=:profile GROUP BY apply_status
                        """
                    ),
                    {"profile": profile},
                ).mappings()
            }
            by_app = {
                r["status"]: r["n"]
                for r in c.execute(
                    text(
                        """
                        SELECT status, COUNT(*) AS n FROM applications
                        WHERE profile=:profile GROUP BY status
                        """
                    ),
                    {"profile": profile},
                ).mappings()
            }
            queued_row = (
                c.execute(
                    text(
                        """
                        SELECT COUNT(*) AS n FROM vacancies
                        WHERE profile=:profile
                          AND apply_status='queued' AND filter_status='ok'
                        """
                    ),
                    {"profile": profile},
                )
                .mappings()
                .fetchone()
            )
            queued = int(queued_row["n"]) if queued_row else 0
        return {
            "by_category": by_cat,
            "by_apply_status": by_apply,
            "applications": by_app,
            "queued": queued,
            "high": int(by_cat.get("HIGH", 0)),
            "medium": int(by_cat.get("MEDIUM", 0)),
            "low": int(by_cat.get("LOW", 0)),
            "applied": int(by_app.get("applied", 0)),
        }


class _JobStateRepo:
    def __init__(self, uow: PostgresUnitOfWork) -> None:
        self._uow = uow

    def set_status(
        self,
        profile: str,
        status: JobStatus | str,
        message: str = "",
        stats: dict[str, Any] | None = None,
    ) -> None:
        st = status.value if isinstance(status, JobStatus) else str(status)
        with self._uow._conn() as c:
            existing = (
                c.execute(
                    text("SELECT stats_json FROM job_state WHERE profile=:profile"),
                    {"profile": profile},
                )
                .mappings()
                .fetchone()
            )
            if stats is None and existing:
                stats_json = existing["stats_json"] or "{}"
            else:
                stats_json = json.dumps(stats or {}, ensure_ascii=False)
            c.execute(
                text(
                    """
                    INSERT INTO job_state(profile, status, message, stats_json, updated_at)
                    VALUES (:profile, :status, :message, :stats_json, :ts)
                    ON CONFLICT(profile) DO UPDATE SET
                        status=EXCLUDED.status,
                        message=EXCLUDED.message,
                        stats_json=EXCLUDED.stats_json,
                        updated_at=EXCLUDED.updated_at
                    """
                ),
                {
                    "profile": profile,
                    "status": st,
                    "message": message,
                    "stats_json": stats_json,
                    "ts": time.time(),
                },
            )

    def get_status(self, profile: str) -> JobState:
        with self._uow._conn() as c:
            row = (
                c.execute(
                    text("SELECT * FROM job_state WHERE profile=:profile"),
                    {"profile": profile},
                )
                .mappings()
                .fetchone()
            )
        if not row:
            return JobState(profile=profile)
        try:
            status = JobStatus(row["status"])
        except ValueError:
            status = JobStatus.IDLE
        return JobState(
            profile=row["profile"],
            status=status,
            message=row["message"] or "",
            stats=json.loads(row["stats_json"] or "{}"),
            updated_at=row["updated_at"],
        )


class _JournalRepo:
    def __init__(self, uow: PostgresUnitOfWork) -> None:
        self._uow = uow

    def log(
        self,
        profile: str,
        event: str,
        message: str = "",
        level: str = "info",
        payload: dict[str, Any] | None = None,
        *,
        service: str | None = None,
    ) -> None:
        svc = normalize_journal_service(service, event=event)
        with self._uow._conn() as c:
            c.execute(
                text(
                    """
                    INSERT INTO journal(ts, profile, level, event, message, payload, service)
                    VALUES (:ts, :profile, :level, :event, :message, :payload, :service)
                    """
                ),
                {
                    "ts": time.time(),
                    "profile": profile,
                    "level": level,
                    "event": event,
                    "message": message,
                    "payload": json.dumps(payload or {}, ensure_ascii=False),
                    "service": svc,
                },
            )

    def recent(
        self,
        profile: str | None = None,
        limit: int = 80,
        *,
        service: str | None = None,
        offset: int = 0,
    ) -> list[JournalEntry]:
        svc = normalize_journal_service(service) if service else None
        with self._uow._conn() as c:
            if profile and svc:
                rows = (
                    c.execute(
                        text(
                            """
                            SELECT * FROM journal WHERE profile=:profile AND service=:service
                            ORDER BY ts DESC LIMIT :limit OFFSET :offset
                            """
                        ),
                        {
                            "profile": profile,
                            "service": svc,
                            "limit": limit,
                            "offset": offset,
                        },
                    )
                    .mappings()
                    .fetchall()
                )
            elif profile:
                rows = (
                    c.execute(
                        text(
                            """
                            SELECT * FROM journal WHERE profile=:profile
                            ORDER BY ts DESC LIMIT :limit OFFSET :offset
                            """
                        ),
                        {"profile": profile, "limit": limit, "offset": offset},
                    )
                    .mappings()
                    .fetchall()
                )
            elif svc:
                rows = (
                    c.execute(
                        text(
                            """
                            SELECT * FROM journal WHERE service=:service
                            ORDER BY ts DESC LIMIT :limit OFFSET :offset
                            """
                        ),
                        {"service": svc, "limit": limit, "offset": offset},
                    )
                    .mappings()
                    .fetchall()
                )
            else:
                rows = (
                    c.execute(
                        text(
                            "SELECT * FROM journal ORDER BY ts DESC LIMIT :limit OFFSET :offset"
                        ),
                        {"limit": limit, "offset": offset},
                    )
                    .mappings()
                    .fetchall()
                )
        out: list[JournalEntry] = []
        for r in rows:
            out.append(
                JournalEntry(
                    id=r["id"],
                    ts=r["ts"],
                    profile=r["profile"],
                    level=r["level"],
                    event=r["event"],
                    message=r["message"] or "",
                    payload=json.loads(r["payload"] or "{}"),
                    service=normalize_journal_service(
                        r["service"] if "service" in r else None,
                        event=r["event"],
                    ),
                )
            )
        return out


class _LinkedInContactRepo:
    def __init__(self, uow: PostgresUnitOfWork) -> None:
        self._uow = uow

    def upsert(self, contact: LinkedInContact) -> int:
        now = time.time()
        with self._uow._conn() as c:
            c.execute(
                text(
                    """
                    INSERT INTO linkedin_contacts(
                        profile, url, name, headline, location, query,
                        status, error, created_at, updated_at
                    ) VALUES (
                        :profile, :url, :name, :headline, :location, :query,
                        :status, :error, :created_at, :updated_at
                    )
                    ON CONFLICT(profile, url) DO UPDATE SET
                        name=COALESCE(EXCLUDED.name, linkedin_contacts.name),
                        headline=COALESCE(EXCLUDED.headline, linkedin_contacts.headline),
                        location=COALESCE(EXCLUDED.location, linkedin_contacts.location),
                        query=COALESCE(EXCLUDED.query, linkedin_contacts.query),
                        status=EXCLUDED.status,
                        error=EXCLUDED.error,
                        updated_at=EXCLUDED.updated_at
                    """
                ),
                {
                    "profile": contact.profile,
                    "url": contact.url,
                    "name": contact.name,
                    "headline": contact.headline,
                    "location": contact.location,
                    "query": contact.query,
                    "status": contact.status,
                    "error": contact.error,
                    "created_at": now,
                    "updated_at": now,
                },
            )
            row = (
                c.execute(
                    text(
                        """
                        SELECT id FROM linkedin_contacts
                        WHERE profile=:profile AND url=:url
                        """
                    ),
                    {"profile": contact.profile, "url": contact.url},
                )
                .mappings()
                .fetchone()
            )
            assert row is not None
            return int(row["id"])

    def list_for_profile(
        self, profile: str, limit: int = 200, offset: int = 0
    ) -> list[LinkedInContact]:
        with self._uow._conn() as c:
            rows = (
                c.execute(
                    text(
                        """
                        SELECT * FROM linkedin_contacts WHERE profile=:profile
                        ORDER BY updated_at DESC LIMIT :limit OFFSET :offset
                        """
                    ),
                    {"profile": profile, "limit": limit, "offset": offset},
                )
                .mappings()
                .fetchall()
            )
        return [_row_li_contact(r) for r in rows]

    def stats(self, profile: str) -> dict[str, Any]:
        with self._uow._conn() as c:
            by_status = {
                r["status"]: r["n"]
                for r in c.execute(
                    text(
                        """
                        SELECT status, COUNT(*) AS n FROM linkedin_contacts
                        WHERE profile=:profile GROUP BY status
                        """
                    ),
                    {"profile": profile},
                ).mappings()
            }
            total_row = (
                c.execute(
                    text(
                        "SELECT COUNT(*) AS n FROM linkedin_contacts WHERE profile=:profile"
                    ),
                    {"profile": profile},
                )
                .mappings()
                .fetchone()
            )
            total = int(total_row["n"]) if total_row else 0
        return {"by_status": by_status, "total": total}


class _LinkedInVacancyRepo:
    def __init__(self, uow: PostgresUnitOfWork) -> None:
        self._uow = uow

    def upsert(self, vacancy: LinkedInVacancyLink) -> int:
        now = time.time()
        with self._uow._conn() as c:
            c.execute(
                text(
                    """
                    INSERT INTO linkedin_vacancies(
                        profile, url, title, company, location, query, source,
                        created_at, updated_at
                    ) VALUES (
                        :profile, :url, :title, :company, :location, :query, :source,
                        :created_at, :updated_at
                    )
                    ON CONFLICT(profile, url) DO UPDATE SET
                        title=COALESCE(EXCLUDED.title, linkedin_vacancies.title),
                        company=COALESCE(EXCLUDED.company, linkedin_vacancies.company),
                        location=COALESCE(EXCLUDED.location, linkedin_vacancies.location),
                        query=COALESCE(EXCLUDED.query, linkedin_vacancies.query),
                        updated_at=EXCLUDED.updated_at
                    """
                ),
                {
                    "profile": vacancy.profile,
                    "url": vacancy.url,
                    "title": vacancy.title,
                    "company": vacancy.company,
                    "location": vacancy.location,
                    "query": vacancy.query,
                    "source": vacancy.source or "linkedin",
                    "created_at": now,
                    "updated_at": now,
                },
            )
            row = (
                c.execute(
                    text(
                        """
                        SELECT id FROM linkedin_vacancies
                        WHERE profile=:profile AND url=:url
                        """
                    ),
                    {"profile": vacancy.profile, "url": vacancy.url},
                )
                .mappings()
                .fetchone()
            )
            assert row is not None
            return int(row["id"])

    def exists(self, profile: str, *, url: str | None = None) -> bool:
        url = (url or "").strip()
        if not url:
            return False
        with self._uow._conn() as c:
            row = c.execute(
                text(
                    """
                    SELECT 1 FROM linkedin_vacancies
                    WHERE profile=:profile AND url=:url
                    LIMIT 1
                    """
                ),
                {"profile": profile, "url": url},
            ).fetchone()
        return row is not None

    def known_urls(self, profile: str) -> set[str]:
        with self._uow._conn() as c:
            rows = (
                c.execute(
                    text(
                        "SELECT url FROM linkedin_vacancies WHERE profile=:profile"
                    ),
                    {"profile": profile},
                )
                .mappings()
                .fetchall()
            )
        return {(r["url"] or "").strip() for r in rows if (r["url"] or "").strip()}

    def list_for_profile(
        self, profile: str, limit: int = 200, offset: int = 0
    ) -> list[LinkedInVacancyLink]:
        with self._uow._conn() as c:
            rows = (
                c.execute(
                    text(
                        """
                        SELECT * FROM linkedin_vacancies WHERE profile=:profile
                        ORDER BY updated_at DESC LIMIT :limit OFFSET :offset
                        """
                    ),
                    {"profile": profile, "limit": limit, "offset": offset},
                )
                .mappings()
                .fetchall()
            )
        return [_row_li_vacancy(r) for r in rows]

    def stats(self, profile: str) -> dict[str, Any]:
        with self._uow._conn() as c:
            total_row = (
                c.execute(
                    text(
                        "SELECT COUNT(*) AS n FROM linkedin_vacancies WHERE profile=:profile"
                    ),
                    {"profile": profile},
                )
                .mappings()
                .fetchone()
            )
            total = int(total_row["n"]) if total_row else 0
        return {"total": total}


class _ReportFileRepo:
    def __init__(self, uow: PostgresUnitOfWork) -> None:
        self._uow = uow

    def record(
        self,
        profile: str,
        kind: str,
        path: str,
        *,
        scheduled: bool = False,
    ) -> int:
        with self._uow._conn() as c:
            row = (
                c.execute(
                    text(
                        """
                        INSERT INTO report_files(profile, kind, path, created_at, scheduled)
                        VALUES (:profile, :kind, :path, :ts, :scheduled)
                        RETURNING id
                        """
                    ),
                    {
                        "profile": profile,
                        "kind": kind,
                        "path": path,
                        "ts": time.time(),
                        "scheduled": int(scheduled),
                    },
                )
                .mappings()
                .fetchone()
            )
            return int(row["id"]) if row else 0

    def list_recent(self, limit: int = 30) -> list[dict[str, Any]]:
        with self._uow._conn() as c:
            rows = (
                c.execute(
                    text(
                        """
                        SELECT * FROM report_files
                        ORDER BY created_at DESC LIMIT :limit
                        """
                    ),
                    {"limit": limit},
                )
                .mappings()
                .fetchall()
            )
        return [
            {
                "id": r["id"],
                "profile": r["profile"],
                "kind": r["kind"],
                "path": r["path"],
                "created_at": r["created_at"],
                "scheduled": bool(r["scheduled"]),
            }
            for r in rows
        ]

    def last_scheduled(self) -> dict[str, Any] | None:
        with self._uow._conn() as c:
            row = (
                c.execute(
                    text(
                        """
                        SELECT * FROM report_files WHERE scheduled=1
                        ORDER BY created_at DESC LIMIT 1
                        """
                    )
                )
                .mappings()
                .fetchone()
            )
        if not row:
            return None
        return {
            "id": row["id"],
            "profile": row["profile"],
            "kind": row["kind"],
            "path": row["path"],
            "created_at": row["created_at"],
            "scheduled": True,
        }


def _clean_profile_name(name: str, *, fallback: str | None = None) -> str:
    cleaned = (name or "").strip()
    if not cleaned:
        if fallback is not None:
            return fallback
        raise ValueError("empty profile name")
    if len(cleaned) > 64:
        raise ValueError("profile name too long")
    if cleaned in (".", "..") or any(ch in cleaned for ch in ("/", "\\", "\0")):
        raise ValueError("invalid profile name")
    return cleaned


def _row_profile(r: RowLike) -> Profile:
    return Profile(
        name=r["name"],
        storage_path=r["storage_path"],
        storage_saved_at=r["storage_saved_at"],
        notes=r["notes"],
        created_at=r["created_at"],
    )


def _row_vacancy(r: RowLike) -> Vacancy:
    try:
        cat = FitCategory(r["category"] or "LOW")
    except ValueError:
        cat = FitCategory.LOW
    try:
        apply = ApplyStatus(r["apply_status"] or "queued")
    except ValueError:
        apply = ApplyStatus.QUEUED
    return Vacancy(
        id=r["id"],
        profile=r["profile"],
        vacancy_id=r["vacancy_id"],
        url=r["url"],
        title=r["title"] or "",
        description=r["description"] or "",
        query=r["query"] or "",
        serp_url=r["serp_url"] or "",
        category=cat,
        score=int(r["score"] or 0),
        category_reason=r["category_reason"] or "",
        filter_status=r["filter_status"] or "pending",
        apply_status=apply,
        created_at=r["created_at"],
        updated_at=r["updated_at"],
    )


def _row_li_contact(r: RowLike) -> LinkedInContact:
    return LinkedInContact(
        id=r["id"],
        profile=r["profile"],
        url=r["url"],
        name=r["name"] or "",
        headline=r["headline"] or "",
        location=r["location"] or "",
        query=r["query"] or "",
        status=r["status"] or "pending",
        error=r["error"],
        created_at=r["created_at"],
        updated_at=r["updated_at"],
    )


def _row_li_vacancy(r: RowLike) -> LinkedInVacancyLink:
    return LinkedInVacancyLink(
        id=r["id"],
        profile=r["profile"],
        url=r["url"],
        title=r["title"] or "",
        company=r["company"] or "",
        location=r["location"] or "",
        query=r["query"] or "",
        source=r["source"] or "linkedin",
        created_at=r["created_at"],
        updated_at=r["updated_at"],
    )
